name: javascript-ci

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - "javascript/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false

    strategy:
      matrix:
        node-version: [20.x, 22.x, 24.x]

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8.15.4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - run: pnpm install --frozen-lockfile
        working-directory: javascript
      - run: pnpm run lint
        working-directory: javascript
      - run: pnpm run build
        working-directory: javascript
      - run: cd examples/vitest && rm -rf pnpm-lock.yaml && pnpm install --force
        working-directory: javascript/examples/vitest
      - run: pnpm run test
        working-directory: javascript/examples/vitest
