name: javascript-ci

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - "javascript/**"
      - ".github/workflows/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false

    strategy:
      matrix:
        node-version: [24.x]

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 10.12.1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          cache-dependency-path: "javascript/pnpm-lock.yaml"
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        working-directory: javascript

      - name: Build
        run: pnpm run build
        working-directory: javascript

      - name: Install example dependencies
        run: pnpm install --frozen-lockfile
        working-directory: javascript/examples/vitest

      - name: Lint
        run: pnpm run lint
        working-directory: javascript

      - name: Test (Examples)
        run: pnpm run test
        env:
          LANGWATCH_API_KEY: ${{ secrets.LANGWATCH_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        working-directory: javascript/examples/vitest
