name: python-publish

on:
  release:
    types:
      - published
  workflow_dispatch:

permissions:
  contents: read

jobs:
  publish:
    if: startsWith(github.event.release.tag_name, 'python/') || (github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          make install
          uv pip install build
        working-directory: python

      - name: Build package
        run: uv run python -m build
        working-directory: python

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
        working-directory: python
        with:
          packages_dir: dist/
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
